#!/usr/bin/env bash
# ==============================================================================
# Cloudflare DDNS Installer
# ==============================================================================

set -euo pipefail

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This installer must be run as root (sudo ./install.sh)" >&2
    exit 1
fi

echo "======================================"
echo " Cloudflare DDNS Setup"
echo "======================================"
echo ""

# --- 依赖解析 ---
MISSING_DEPS=()
for dep in jq curl ca-certificates; do
    if ! dpkg -s "$dep" &> /dev/null && ! command -v "$dep" &> /dev/null; then
        MISSING_DEPS+=("$dep")
    fi
done

if [ ${#MISSING_DEPS[@]} -ne 0 ]; then
    echo "INFO: Installing missing dependencies: ${MISSING_DEPS[*]}"
    if command -v apt-get &> /dev/null; then
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${MISSING_DEPS[@]}"
        echo "SUCCESS: Dependencies installed."
    else
        echo "CRITICAL: Package manager 'apt-get' not found. Please install manually: ${MISSING_DEPS[*]}" >&2
        exit 1
    fi
fi

# --- 交互式配置 ---
read -r -p "Cloudflare API Token (Required): " IN_CF_API_TOKEN
if [ -z "$IN_CF_API_TOKEN" ]; then
    echo "ERROR: API Token is required. Aborting." >&2
    exit 1
fi

read -r -p "Cloudflare Zone Name [Default: zhec.org]: " IN_CF_ZONE_NAME
IN_CF_ZONE_NAME=${IN_CF_ZONE_NAME:-zhec.org}

read -r -p "DNS Record Name [Default: www.zhec.org]: " IN_CF_RECORD_NAME
IN_CF_RECORD_NAME=${IN_CF_RECORD_NAME:-www.zhec.org}

read -r -p "DNS Record Type [Default: A]: " IN_CF_RECORD_TYPE
IN_CF_RECORD_TYPE=${IN_CF_RECORD_TYPE:-A}

read -r -p "TTL in seconds (1 = Auto) [Default: 60]: " IN_CF_TTL
IN_CF_TTL=${IN_CF_TTL:-60}

read -r -p "Proxied through Cloudflare? (true/false) [Default: false]: " IN_CF_PROXIED
IN_CF_PROXIED=${IN_CF_PROXIED:-false}

echo "--- Optional Telegram Notifications ---"
read -r -p "Telegram Bot Token [Leave empty to disable]: " IN_TG_BOT_TOKEN
if [ -n "$IN_TG_BOT_TOKEN" ]; then
    read -r -p "Telegram Chat ID: " IN_TG_CHAT_ID
else
    IN_TG_CHAT_ID=""
fi

read -r -p "Check interval in minutes [Default: 5]: " CHECK_INTERVAL
CHECK_INTERVAL=${CHECK_INTERVAL:-5}

# --- 部署 ---
CONFIG_DIR="/etc/cf-ddns"
CACHE_DIR="/var/lib/cf-ddns"
BIN_PATH="/usr/local/bin/cf-ddns-update"
CONFIG_FILE="${CONFIG_DIR}/${IN_CF_RECORD_NAME}.env"

# 幂等性保障
if systemctl is-active --quiet cf-ddns.timer; then
    echo "INFO: Stopping existing systemd timer..."
    systemctl stop cf-ddns.timer
fi

echo "INFO: Creating system directories..."
mkdir -p "$CONFIG_DIR"
# 为支持安装后立即进行手动测试运行，这里依然创建 Cache Dir 
# (即使 Systemd 的 StateDirectory 特性最终会接管它)
mkdir -p "$CACHE_DIR"
chmod 700 "$CONFIG_DIR" "$CACHE_DIR"

echo "INFO: Generating secure environment configuration at $CONFIG_FILE..."
# 通过 printf %q 拦截任何用户可能注入的命令或特殊转义字符
cat <<EOF > "$CONFIG_FILE"
# Auto-generated by install.sh - $(date)
CF_API_TOKEN=$(printf '%q' "$IN_CF_API_TOKEN")
CF_ZONE_NAME=$(printf '%q' "$IN_CF_ZONE_NAME")
CF_RECORD_NAME=$(printf '%q' "$IN_CF_RECORD_NAME")
CF_RECORD_TYPE=$(printf '%q' "$IN_CF_RECORD_TYPE")
CF_TTL=$(printf '%q' "$IN_CF_TTL")
CF_PROXIED=$(printf '%q' "$IN_CF_PROXIED")

TG_BOT_TOKEN=$(printf '%q' "$IN_TG_BOT_TOKEN")
TG_CHAT_ID=$(printf '%q' "$IN_TG_CHAT_ID")
EOF
chmod 600 "$CONFIG_FILE"

echo "INFO: Installing updater binary..."
cp ddns-update.sh "$BIN_PATH"
chmod 700 "$BIN_PATH"

echo "INFO: Deploying systemd unit files..."
SERVICE_PATH="/etc/systemd/system/cf-ddns.service"
TIMER_PATH="/etc/systemd/system/cf-ddns.timer"

sed "s|{{CONFIG_PATH}}|$CONFIG_FILE|g" systemd/cf-ddns.service > "$SERVICE_PATH"
sed "s|{{INTERVAL}}|$CHECK_INTERVAL|g" systemd/cf-ddns.timer > "$TIMER_PATH"

chmod 644 "$SERVICE_PATH" "$TIMER_PATH"

echo "INFO: Reloading systemd daemon and enabling scheduled timer..."
systemctl daemon-reload
systemctl enable cf-ddns.timer
systemctl start cf-ddns.timer

echo ""
echo "======================================"
echo " ✅ Installation Complete"
echo "======================================"
echo "• The updater runs automatically every $CHECK_INTERVAL minute(s)."
echo "• Configuration is securely stored at: $CONFIG_FILE"
echo ""
echo "Verify configuration manually:"
echo "  sudo $BIN_PATH $CONFIG_FILE"
echo ""
echo "Monitor automated runs:"
echo "  sudo journalctl -u cf-ddns.service -f"
echo "======================================"
